### ■ 예제41. 지역변수와 전역변수 이해하기
#### 변수는 자신이 생성된 범위(코드블럭) 안에서만 유효하다
#### 함수 안에서 만든 변수는 함수 안에서만 살아있다가 함수 코드의 실행이 종료되면 그 생명을 다한다 : 지역변수

#### 이와는 반대로 함수 외부에서 만든 변수는 프로그램이 살아있는 동안에 함께 살아있다가 프로그램이 종료되면 같이 소멸된다.
#### 이렇게 프로그램 전체를 유효범위로 가지는 변수 : 전역변수 

In [1]:
# 예제1
strdata = '전역변수'

def func1():
    strdata='지역변수'
    return strdata

print(func1())
print(strdata)

지역변수
전역변수


#### 대부분 많은 코드들이 지역변수를 사용한다
#### 전역변수를 사용하는 경우는
    프로그램 전체에서 공통적으로 사용되고 잘 변하지 않는 데이터는 전역변수로 사용함

In [2]:
# 예제2
pi=3.141592653589793

def cycle_func1(v_r):
    global pi
    return (pi*v_r*v_r)

def cycle_func2(v_r):
    global pi
    return (1/4*(pi*v_r*v_r))

cycle_func1(5)


78.53981633974483

### ■ 예제42. 리턴 값 이해하기(return)
#### 모든 함수는 이름을 갖고 있다. 이 이름을 불러주면 파이썬은 그 이름 아래에 정의 되어있는 코드를 실행한다. 이 때 함수를 부르는 코드를 호출자라 한다.
#### 함수가 호출자에게 결과를 돌려주는 것을 반환(return)이라 한다

In [3]:
# 절댓값을 출력하는 함수
print(abs(-9))
print(abs(9))

9
9


### ※ 문제90. abs 함수를 사용하지 말고 if문을 이용해서 절댓값을 출력하는 my_abs라는 함수를 생성하시오

In [4]:
def my_abs(n):
    if n>=0:
        n=n
    else:
        n=-n
    return n

print(my_abs(-9))

9


### ※ 문제91. (파이썬 알고리즘 문제 17번) 오라클의 instr 함수를 파이썬으로 생성하시오

In [5]:
def instr(a,b):
    ls=[]
    for i in range(len(a)):
        ls.append(a[i])
        if ls[i]==b:
            return i+1
    return 0    
print(instr('smith','s'))
print(instr('smith','m'))
print(instr('smith','k'))

1
2
0


In [6]:
def instr2(a,n):
    for i in range(len(a)):
        if a[i]==n:
            return i+1
            break

instr2('smith','i')

3

### ※ 문제92. 오라클 개발자가 만든 것 처럼 아래의 결과가 0이 나오게 함수를 만드시오

In [7]:
def instr(a,b):
    for i in range(len(a)):
            if a[i]==b:
                return i+1
    return 0
            
print(instr('smith','k'))
print(instr('smith','m'))

0
2


### ■ 예제43. 파이썬 모듈 이해하기
#### 파이썬에서는 각각의 소스 파일을 일컬어 모듈이라고 한다.
#### 이미 만들어져 있고 안정성이 검증된 함수들을 성격에 맞게 하나의 파일로 묶어 놓은 것을 모듈이라고 한다.
#### 외부의 모듈에 있는 함수를 사용하려면 이 모듈을 먼저 우리 코드로 가져와서 자유롭게 사용할 수 있도록 해야하는데
#### 파이썬에서는 모듈을 import 한다고 한다

In [8]:
import time

print('5초간 프로그램을 정지합니다.')
time.sleep(5)
print('5초가 지났습니다.')

5초간 프로그램을 정지합니다.
5초가 지났습니다.


### ※ 문제93. 메모장을 열고 instr 함수와 initcap 함수를 붙여넣고 oracle.py라는 이름으로 저장

In [9]:
import oracle

print(oracle.instr('smith','m'))

ModuleNotFoundError: No module named 'oracle'

### ■ 예제44. 파이썬 패키지 이해하기
#### 우리가 음악파일을 저장할 때도 장르별로 폴더를 만들어서 별도로 저장하듯 파이썬 모듈도 음악처럼 갯수가 많아지면 폴더(모듈 꾸러미)별로 별도 관리를 해야 관리가 편함
#### 이 폴더가 바로 '패키지'

#### 파이썬 패키지 만드는 단계
1. 패키지 저장할 폴더(my_loc)를 working directory 안에 생성
2. module 파일을 해당 폴더에 추가
3. 이 폴더가 패키지로 인정을 받으려면 반드시 갖고있어야 하는 파일이 있다.   
``` __init__.py```
4. 아래의 코드를 실행한다  
```python
from my_loc import oracle
print (oracle.instr('smith','m')```

In [10]:
from my_loc import oracle

print(oracle.instr('smith','m'))

2


### ※ 문제94. 패키지 안에 `__init__.py`를 비워두는게 보통인데 이 파일의 내용을 채워넣는 경우는 언제인가?
#### 답: `__init__.py`에 아래의 내용을 적고 저장한다
```python
__all__=['oracle','machine_learn','deep_learn']
```
위와 같이 작성하면 아래와 같이 코드를 작성할 수 있게 된다
```python
from my_loc import *
```

### ■ 예제45. 파이썬 모듈 import 이해하기 (import)
#### 이미 만들어져 있는 어떤 함수를 우리가 작성하는 코드에서 자유롭게 활용할 수 있으려면 해당 함수가 포함된 모듈을 import 해야 한다.
#### import 하는 방법은 다음과 같다
```python
import 모듈이름
from 패키지명 import 모듈이름
import 패키지명.모듈이름
```


In [11]:
# 예제
import pandas as pd
import numpy as np
import time

#### 패키지 이름을 안주고 모듈만 import 했는데 잘 실행이 되는 이유
1. 파이썬 내장 모듈
2. sys.path에 정의되어 있는 모듈    

```      
※ import를 만나면 파이썬 모듈을 찾는 순서
1. 파이썬 내장 모듈 검색
2. sys.path 에 정의되어 있는 디렉토리 검색
```

In [12]:
# 파이썬 내장 모듈이 무엇이 있는지 확인하는 방법
import sys
print(sys.builtin_module_names)

('_abc', '_ast', '_bisect', '_blake2', '_codecs', '_codecs_cn', '_codecs_hk', '_codecs_iso2022', '_codecs_jp', '_codecs_kr', '_codecs_tw', '_collections', '_contextvars', '_csv', '_datetime', '_functools', '_heapq', '_imp', '_io', '_json', '_locale', '_lsprof', '_md5', '_multibytecodec', '_opcode', '_operator', '_pickle', '_random', '_sha1', '_sha256', '_sha3', '_sha512', '_signal', '_sre', '_stat', '_string', '_struct', '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', '_winapi', 'array', 'atexit', 'audioop', 'binascii', 'builtins', 'cmath', 'errno', 'faulthandler', 'gc', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'parser', 'sys', 'time', 'winreg', 'xxsubtype', 'zipimport', 'zlib')


In [13]:
# sys.path에 정의된 디렉토리가 무엇인지 확인하는 방법
import sys
for path in sys.path:
    print(path)

K:\Itwill\2. Python
C:\Users\knitwill\anaconda3\python37.zip
C:\Users\knitwill\anaconda3\DLLs
C:\Users\knitwill\anaconda3\lib
C:\Users\knitwill\anaconda3

C:\Users\knitwill\anaconda3\lib\site-packages
C:\Users\knitwill\anaconda3\lib\site-packages\win32
C:\Users\knitwill\anaconda3\lib\site-packages\win32\lib
C:\Users\knitwill\anaconda3\lib\site-packages\Pythonwin
C:\Users\knitwill\anaconda3\lib\site-packages\IPython\extensions
C:\Users\knitwill\.ipython


#### □ site-package
#### 파이썬의 기본 라이브러리 패키지 외에 추가적인 패키지를 설치하는 디렉토리
#### site-packages 디렉토리에 여러가지 소프트웨어가 사용할 공통 모듈을 넣어두면 물리적인 장소에 구애받지 않고 모듈에 접근하여 반입할 수 있다.

### ※ 문제95. my_loc 폴더를 site-packages 디렉토리에 복사

In [14]:
from my_loc import oracle

oracle.initcap('seojun')

'Seojun'

### ■ 예제46. numpy 모듈 사용하기
#### numpy : python 언어에서 기본적으로 지원하지 않는 배열(array) 또는 행렬(matrix)의 계산을 숩기 해주는 라이브러리
#### ML에서 많이 사용하는 선형대수학에 관련된 수식들을 python에서 쉽게 프로그래밍 할 수 있게 해준다.

### ※ 문제96. 아래의 행렬을 numpy array로 생성하시오
$$
    \begin{pmatrix}
    1 & 2 \\
    4 & 7 \\
    \end{pmatrix}
    +
    \begin{pmatrix}
    \end{pmatrix}
$$

In [17]:
# 1. list로만 했을 때
a=[[1,2],[4,7]]
a

[[1, 2], [4, 7]]

In [16]:
# 2. numpy array로 했을 때
import numpy as np
b=np.array([[1,2],[4,7]])
b

array([[1, 2],
       [4, 7]])

### ※ 문제97. 아래의 행렬의 합을 numpy로 구현하시오
$$
\begin{pmatrix}
1 & 2 \\
4 & 5 \\
\end{pmatrix}
+
\begin{pmatrix}
3 & 1 \\
6 & 2 \\
\end{pmatrix}
$$

In [18]:
a=np.array([[1,2],[4,5]])
b=np.array([[3,1],[6,2]])
a+b

array([[ 4,  3],
       [10,  7]])

### ※ 문제98. 아래의 행렬의 곱을 먼저 손으로 구하시오
$$
\begin{pmatrix}
1&2 \\
3&4 \\
\end{pmatrix}
*
\begin{pmatrix}
2&3\\
1&4\\
\end{pmatrix}
$$

$$
\begin{pmatrix}
4&11\\
10&25\\
\end{pmatrix}
$$

In [20]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[1,4]])
np.dot(a,b)

array([[ 4, 11],
       [10, 25]])

### ※ 문제99. 아래의 행렬의 곱을 numpy로 구현하시오
$$
\begin{pmatrix}
1&2&3\\
4&5&6\\
\end{pmatrix}
*
\begin{pmatrix}
5&6\\
7&8\\
9&10\\
\end{pmatrix}
$$

In [21]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6],[7,8],[9,10]])
np.dot(a,b)

array([[ 46,  52],
       [109, 124]])

### ※ 문제100. 아래의 행렬의 3제곱을 출력하시오
$$
\begin{pmatrix}
1&2\\
3&4\\
\end{pmatrix}
$$

In [25]:
import numpy as np

a=np.array([[1,2],[3,4]])
print(np.dot(a,a).dot(a))            

[[ 37  54]
 [ 81 118]]


### ※(생각해야할 문제) 문제98번을 for loop문으로 구현하시오

In [70]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[1,4]])
rs=np.zeros((2,2))
for i in range(len(a)):      
    for j in range(len(b)):  
        for k in range(len(a)):
            rs[i][j]+=a[i][k]*b[k][j]
rs        

array([[ 4., 11.],
       [10., 25.]])

### ※(오늘의 마지막 문제)(파이썬 알고리즘 문제 18번) 탐욕 알고리즘을 파이썬으로 구현하시오
#### 금액을 입력하세요 ~ 14
#### 10원 1개, 7원 0개, 1원 4개

In [27]:
a=int(input('금액을 입력하세요 ~'))
b, q, r= 0,0,0
if a/10 != 0:
    q=int(a/10)
    r=a%10
if r/7 !=0:
    b=int(r/7)
    r=r-b*7
print('10원 %d개 7원 %d개 1원 %d개' %(q,b,r))

금액을 입력하세요 ~14
10원 1개 7원 0개 1원 4개


In [91]:
len(a)

1