### ■ 예제152. 필수 알고리즘1 (합성곱 연산)

### ※ 문제313. 아래의 덧셈 행렬을 numpy를 이용하지 말고 하시오
$$
    \begin{pmatrix}
        1 & 2 \\
        3 & 4 \\
    \end{pmatrix}
+
    \begin{pmatrix}
        10 & 20 \\
        30 & 40 \\
    \end{pmatrix}
$$

In [2]:
a=[[1,2],[3,4]]
b=[[10,20],[30,40]]
c=[]
for i in range(len(a)):
    d=[]
    for j in range(len(b)):
        d.append(a[i][j]+b[i][j])
    c.append(d)
c

[[11, 22], [33, 44]]

### ※ 문제314. 위의 행렬 연산을 numpy를 이용해서 수행하시오

In [4]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c=a+b
c

array([[11, 22],
       [33, 44]])

### ※ Numpy란
python 언어에서 기본적으로 지원하지 않는 배열 혹은 행렬의 계산을 쉽게 해주는 라이브러리  
ML에서 많이 사용하는 선형대수학에 관련한 수식들을 python에서 쉽게 프로그래밍 할 수 있게 해준다


### ※ 문제315. 아래의 행렬을 numpy array로 만드시오
$$
    \begin{pmatrix}
    1 & 6 \\
    7 & 3 \\
    \end{pmatrix}
    $$
    

In [10]:
import numpy as np
A = np.array([[1,6],[7,3]])
A

array([[1, 6],
       [7, 3]])

### ※ 문제316. 아래의 행렬의 각 요소에 숫자 5를 더하시오


In [11]:
A+5

array([[ 6, 11],
       [12,  8]])

### Numpy로 행렬 연산을 했을 때 중요한 기능 "브로드캐스트"
#### 브로드캐스트(broadcast)
    Numpy에서는 형상이 다른 배열끼리도 계산을 할 수 있다.
    예를 들면
![그림](http://cfile257.uf.daum.net/image/9997013F5ED46A40104E50)  
![그림2](http://cfile297.uf.daum.net/image/99E8A43F5ED46A400E5851)  

    10이라는 스칼라 값이 2x2 행렬로 확대된 후 연산
    Numpy가 제공하는 브로드캐스트 기능 덕분에 형상이 다른 배열끼리 연산을 스마트하게 할 수 있게 됨


### ※ 문제317. 아래의 행렬이 브로드캐스트 되는지 확인해보시오

In [12]:
B=np.array([[1,2,],[3,4]])
B*[10,20]

array([[10, 40],
       [30, 80]])

### ※ 합성곱(Convolution)
#### 이미지의 형상을 무시하지 않고 이미지를 그대로 인공신경망이 학습할 수 있게 해준 수학 행렬 연산

합성곱에서 원본이미지는 학습해야 할 데이터(사진)이고 필터(filter)는 원본이미지에서 특징을 잡아내는데 사용되는 행렬  
특징을 잡아서 feature map을 생성하여 원본이미지의 형태를 이해하는 것

### ※ 문제318. 아래의 두 행렬을 만들고 합성곱 한 결과인 15를 파이썬으로 구현하시오
$$ 
    \begin{bmatrix}
    1 & 2 & 3 & 0 \\
    0 & 1 & 2 & 3 \\
    3 & 0 & 1 & 2 \\
    2 & 3 & 0 & 1 \\
    \end{bmatrix}
$$
<br>
$$
    \begin{bmatrix}
        2 & 0 & 1 \\
        0 & 1 & 2 \\
        1 & 0 & 2 \\
    \end{bmatrix}
$$

In [10]:
x=np.array([[1,2,3],[0,1,2],[3,0,1]])
f=np.array([[2,0,1],[0,1,2],[1,0,2]])
np.sum(x*f)

15

### ※ 문제319. 아래의 4x4 행렬에서 3x3 행렬 영역만 추출하시오

In [19]:
import numpy as np

A=np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])
sub_a1=np.array(A[:3,:3])
np.sum(sub_a1*f)

15

### ※ 문제320. 아래의 결과가 나오게 파이썬 코드를 작성하시오

In [20]:
A=np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])
sub_a3=np.array(A[1:,:3])
sub_a3

array([[0, 1, 2],
       [3, 0, 1],
       [2, 3, 0]])

### ※ 문제321. 아래의 리스트를 행렬 shape 2x2로 변경하시오
```python
rs=[2,3,4,5]
```

In [23]:
rs=[2,3,4,5]
rs=np.array(rs).reshape(2,2)
rs2=np.array(rs).reshape(1,4)
rs3=np.array(rs).reshape(4,1)
rs, rs2, rs3

(array([[2, 3],
        [4, 5]]),
 array([[2, 3, 4, 5]]),
 array([[2],
        [3],
        [4],
        [5]]))

### ※ 문제322. (파이썬 알고리즘 문제 38)아래의 두 행렬을 합성곱하시오(stride=1)
$$ 
    \begin{bmatrix}
    1 & 2 & 3 & 0 \\
    0 & 1 & 2 & 3 \\
    3 & 0 & 1 & 2 \\
    2 & 3 & 0 & 1 \\
    \end{bmatrix} 
    \begin{bmatrix}
        2 & 0 & 1 \\
        0 & 1 & 2 \\
        1 & 0 & 2 \\
    \end{bmatrix}
$$

In [62]:
A=np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])
f=np.array([[2,0,1],[0,1,2],[1,0,2]])
x=np.zeros([2,2])
for i in range(len(A)-len(f)+1):
    for j in range(int(len(A[0])-len(f[0])+1)):
        x[i][j] = np.sum(A[i:len(f)+i,j:len(f[0])+j]*f)        
x

array([[15., 16.],
       [ 6., 15.]])

### ※ (오늘의 마지막 문제) 오늘 구현한 합성곱 연산을 아래와 같이 함수로 생성해서 구현되게 하시오
```python
convolution(a,filter)
```

In [5]:
def convolution(A,f):
    x=np.zeros([int(len(A)-len(f))+1,int(len(A[0])-len(f[0]))+1])
    
    Ar=int(len(A))
    Ac=int(len(A[0]))
    fr=int(len(f))
    fc=int(len(f[0]))
    
    for i in range(Ar-fr+1):
        for j in range(Ac-fc+1):
            x[i][j] = np.sum(A[i:fr+i,j:fc+j]*f)
    return x

A=np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])
f=np.array([[2,0,1],[0,1,2],[1,0,2]])
convolution(A, f)

array([[15., 16.],
       [ 6., 15.]])

In [21]:
def convolution(A,f):
    x=[]
    
    Ar=int(len(A[0]))
    Ac=int(len(A[0][0]))
    fr=int(len(f[0]))
    fc=int(len(f[0][0]))
    
    for i in range(Ar-fr+1):
        for j in range(Ac-fc+1):
            x.append(np.sum(A[:,i:fr+i,j:fc+j]*f))
    return np.array(x).reshape(2,2)

A=np.array([[[1,2,0,0],[0,1,-2,0],[0,0,1,2],[2,0,0,1]],[[1,0,0,0],[0,0,-2,-1],[3,0,1,0],[2,0,0,1]]])
f=np.array([[[-1,0,3],[2,0,-1],[0,2,1]],[[0,0,0],[2,0,-1],[0,-2,1]]])

print(convolution(A,f))

[[ 5  3]
 [-2 -1]]
