### ■ 예제152. 필수 알고리즘1 (합성곱 연산)

### ※ 문제313. 아래의 덧셈 행렬을 numpy를 이용하지 말고 하시오
$$
    \begin{pmatrix}
        1 & 2 \\
        3 & 4 \\
    \end{pmatrix}
+
    \begin{pmatrix}
        10 & 20 \\
        30 & 40 \\
    \end{pmatrix}
$$

In [2]:
a=[[1,2],[3,4]]
b=[[10,20],[30,40]]
c=[]
for i in range(len(a)):
    d=[]
    for j in range(len(b)):
        d.append(a[i][j]+b[i][j])
    c.append(d)
c

[[11, 22], [33, 44]]

### ※ 문제314. 위의 행렬 연산을 numpy를 이용해서 수행하시오

In [4]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c=a+b
c

array([[11, 22],
       [33, 44]])

### ※ Numpy란
python 언어에서 기본적으로 지원하지 않는 배열 혹은 행렬의 계산을 쉽게 해주는 라이브러리  
ML에서 많이 사용하는 선형대수학에 관련한 수식들을 python에서 쉽게 프로그래밍 할 수 있게 해준다


### ※ 문제315. 아래의 행렬을 numpy array로 만드시오
$$
    \begin{pmatrix}
    1 & 6 \\
    7 & 3 \\
    \end{pmatrix}
    $$
    

In [10]:
import numpy as np
A = np.array([[1,6],[7,3]])
A

array([[1, 6],
       [7, 3]])

### ※ 문제316. 아래의 행렬의 각 요소에 숫자 5를 더하시오


In [11]:
A+5

array([[ 6, 11],
       [12,  8]])

### Numpy로 행렬 연산을 했을 때 중요한 기능 "브로드캐스트"
#### 브로드캐스트(broadcast)
    Numpy에서는 형상이 다른 배열끼리도 계산을 할 수 있다.
    예를 들면
![그림](http://cfile257.uf.daum.net/image/9997013F5ED46A40104E50)  
![그림2](http://cfile297.uf.daum.net/image/99E8A43F5ED46A400E5851)  

    10이라는 스칼라 값이 2x2 행렬로 확대된 후 연산
    Numpy가 제공하는 브로드캐스트 기능 덕분에 형상이 다른 배열끼리 연산을 스마트하게 할 수 있게 됨


### ※ 문제317. 아래의 행렬이 브로드캐스트 되는지 확인해보시오

In [12]:
B=np.array([[1,2,],[3,4]])
B*[10,20]

array([[10, 40],
       [30, 80]])

### ※ 합성곱(Convolution)
#### 이미지의 형상을 무시하지 않고 이미지를 그대로 인공신경망이 학습할 수 있게 해준 수학 행렬 연산